# .streamlit/secrets.toml

[connections.snowflake]
account = "sfcsupport-kjadhav"
user = "stuser"
password = "Admin@123"
role = "strole"
warehouse = "testwarehouse"
database = "pets"
schema = "public"
client_session_keep_alive = true
